// Generated by CoffeeScript 1.6.3
var boxfan, fields, model, prairie, _;

_ = require('understory');

boxfan = require('boxfan');

prairie = require('prairie');

model = function(item, info) {
  if (info.field) {
    item = prairie(item, info.field, info.primary_key);
  }
  if (info.fields) {
    fields(item, info.fields);
  }
  if (_.isObject(info["default"])) {
    item = _.defaults(item, info["default"]);
  }
  if (_.isObject(info.rename)) {
    item = _.rename(item, info.rename);
  }
  if (info.clean) {
    item = _.clean(item);
  }
  if (info.pluck) {
    item = _.pluck(item, info.pluck);
  } else if (info.without) {
    item = _.without(item, info.without);
  }
};

fields = function(item, fields_obj) {
  _.each(fields_obj, function(field_info) {
    if (_.isObject(field_info.field)) {
      if (_.isObject(field_info.filter)) {
        if (boxfan(item, info.filter)) {
          item = prairie(item, field_info.field, info.primary_key);
        }
      } else {
        item = prairie(item, field_info.field, info.primary_key);
      }
    }
  });
};

module.exports = function(items, info) {
  var _this = this;
  if (_.isArray(items)) {
    items = _.map(items, function(item) {
      return model(item, info);
    });
    if (info.filter) {
      items = boxfan(items, info.filter);
    }
    return items;
  } else if (_.isObject(items)) {
    return model(items, info);
  } else {
    return items;
  }
};
